name: build

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8==5.0.4 mypy==1.1.1 mypy-extensions==1.0.0 types-requests==2.28.11.17 typing_extensions==4.5.0 coverage==7.2.2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 test --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 services --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 db --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 services --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 db --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Static type checking with mypy
      run: |
        python -m mypy --strict test
        python -m mypy --strict services
        python -m mypy --strict db
    - name: Unit tests
      run: |
        python -m unittest discover -v
    - name: Generate code coverage reports
      run: |
        python -m coverage run -m unittest discover -v
        python -m coverage lcov -o ./coverage/lcov.info
        python -m coverage report
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
